python -u autoformer_run.py \
  --is_training 1 \
  --root_path ~/data/informer_dataset/midterm \
  --data_path CleanBeijing.csv \
  --model_id beijing_96_48 \
  --model Autoformer \
  --data custom \
  --features S \
  --target TEMP \
  --seq_len 96 \
  --label_len 48 \
  --pred_len 48 \
  --e_layers 2 \
  --d_layers 1 \
  --factor 3 \
  --enc_in 1 \
  --dec_in 1 \
  --c_out 1 \
  --des 'Exp' \
  --exp_id 0 \
  --train_epochs 2